namespace@UFPA
table@Authors
False,0,ID,int,True,
True,0,Name,string,False,
True,0,DOB,DateTime,False,
True,0,PlaceOfBirth,string,False,
True,0,Address,string,False,
True,0,Biography,string,False,
True,0,SignImage,string,False,
True,0,ProfileImage,string,False,
isactiveflag@False
