namespace@UFPA
table@Users
False,0,ID,int,True,Users
True,0,Password,string,False,Users
True,0,Username,string,False,Users
True,0,Name,string,False,Users
True,0,Email,string,False,Users
True,0,Phone,string,False,Users
True,0,SignupDate,string,False,Users
True,0,IsAdmin,bool,False,Users
True,0,IsActive,bool,False,Users
isactiveflag@True
