namespace@UFPA
table@Paintings
False,0,PaintingID,int,True,Paintings
True,0,RegistrationNumber,string,False,Paintings
True,0,Collection,string,False,Paintings
True,0,IsAssignedToAuthor,bool,False,Paintings
True,0,AuthorPaintingID,int,False,Paintings
True,0,Title,string,False,Paintings
True,0,WorkCondition,string,False,Paintings
True,0,WorkConditionDescription,string,False,Paintings
True,0,InventoryNumber,string,False,Paintings
True,0,FrontPhotoPath,string,False,Paintings
True,0,BackPhotoPath,string,False,Paintings
True,0,BeforeRestorationImagePath,string,False,Paintings
True,0,AfterRestorationImagePath,string,False,Paintings
True,0,LastRestorationDate,string,False,Paintings
True,0,DrawerNumber,string,False,Paintings
True,0,CurrentLocation,string,False,Paintings
True,0,LocalLocation,string,False,Paintings
True,0,TagTitle,string,False,Paintings
True,0,Tag,string,False,Paintings
True,0,TagDescription,string,False,Paintings
True,0,Object,string,False,Paintings
True,0,Copy,string,False,Paintings
True,0,CreatedDate,string,False,Paintings
True,0,ModifiedDate,string,False,Paintings
True,0,CultureGroup,string,False,Paintings
True,0,DatePosition,string,False,Paintings
True,0,Style,string,False,Paintings
True,0,Movement,string,False,Paintings
True,0,Period,string,False,Paintings
True,0,SignaturePosition,string,False,Paintings
True,0,SignaturePath,string,False,Paintings
True,0,SinatureDescription,string,False,Paintings
True,0,MarkedPosition,string,False,Paintings
True,0,MarkedPath,string,False,Paintings
True,0,ProcessNumber,string,False,Paintings
True,0,WayOfAcquisition,string,False,Paintings
True,0,DateOfAcquisition,string,False,Paintings
True,0,PurchasePrice,string,False,Paintings
True,0,InsuranceValue,string,False,Paintings
True,0,Publisher,string,False,Paintings
True,0,Edition,string,False,Paintings
True,0,EditionNumber,string,False,Paintings
True,0,TypeOfAge,string,False,Paintings
True,0,Category,string,False,Paintings
True,0,ProviderName,string,False,Paintings
True,0,FrameHeight,string,False,Paintings
True,0,FrameWidth,string,False,Paintings
True,0,FrameDepth,string,False,Paintings
True,0,FrameWeight,string,False,Paintings
True,0,FrameShape,string,False,Paintings
True,0,PrintedAreaHeight,string,False,Paintings
True,0,PrintedAreaWidth,string,False,Paintings
True,0,PrintedAreaDepth,string,False,Paintings
True,0,PrintedAreaWeight,string,False,Paintings
True,0,PrintedAreaShape,string,False,Paintings
True,0,FormalDescription,string,False,Paintings
True,0,ContentDescription,string,False,Paintings
True,0,KeywordsDescription,string,False,Paintings
True,0,ExOwner,string,False,Paintings
True,0,Exhibition,string,False,Paintings
True,0,Reference,string,False,Paintings
True,0,Notes,string,False,Paintings
True,0,PaintingViewCount,int,False,Paintings
True,0,ModifiedBy,int,False,Paintings
True,0,CreatedBy,int,False,Paintings
True,0,IsPhotoAvailable,bool,False,Paintings
True,0,IsRestored,bool,False,Paintings
True,0,IsInTheStore,bool,False,Paintings
True,0,IsSignatureAvailable,bool,False,Paintings
True,0,IsMarked,bool,False,Paintings
isactiveflag@False
